# Generated by Django 5.0.6 on 2024-05-13 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Population',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('tier', models.CharField(max_length=100)),
                ('functgroup', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('work', models.CharField(max_length=100)),
                ('admissiondate', models.CharField(max_length=100)),
            ],
        ),
    ]
