# Generated by Django 5.0.6 on 2024-05-15 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborator',
            fields=[
                ('id_colaborator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('admission_date', models.DateField()),
                ('functional_group', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id_evaluation', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('status', models.BooleanField()),
                ('id_evaluated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_as_evaluated', to='database.colaborator')),
                ('id_evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_as_evaluator', to='database.colaborator')),
            ],
        ),
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=255)),
                ('comment', models.CharField(default='Nada a acrescentar', max_length=255)),
                ('id_evaluation', models.ForeignKey(db_column='id_evaluation', on_delete=django.db.models.deletion.CASCADE, to='database.evaluation')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id_event', models.AutoField(primary_key=True, serialize=False)),
                ('beginning', models.DateField()),
                ('end', models.DateField()),
                ('status', models.BooleanField(default=False)),
                ('evaluated', models.ManyToManyField(related_name='evaluated_events', to='database.colaborator')),
            ],
        ),
        migrations.AddField(
            model_name='evaluation',
            name='id_event',
            field=models.ForeignKey(db_column='id_event', on_delete=django.db.models.deletion.CASCADE, to='database.event'),
        ),
    ]
