# Generated by Django 5.0.6 on 2024-05-15 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_event_evaluator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='evaluator',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluator_events', to='database.colaborator'),
        ),
    ]
