# Generated by Django 5.0.6 on 2024-05-15 16:47

import database.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_alter_event_evaluator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='evaluator',
            field=models.ForeignKey(default=database.models.get_default_evaluator, on_delete=django.db.models.deletion.CASCADE, related_name='evaluator_events', to='database.colaborator'),
        ),
    ]
