# Generated by Django 5.0.6 on 2024-05-14 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_colaborator_criteria_evaluation_event_delete_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborator',
            name='password',
        ),
        migrations.RemoveField(
            model_name='colaborator',
            name='tier',
        ),
        migrations.AlterField(
            model_name='colaborator',
            name='id_colaborator',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='answer',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='id_evaluation',
            field=models.ForeignKey(db_column='id_evaluation', on_delete=django.db.models.deletion.CASCADE, to='database.evaluation'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='id_evaluated',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_as_evaluated', to='database.colaborator'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='id_evaluation',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='id_evaluator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_as_evaluator', to='database.colaborator'),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='id_event',
            field=models.ForeignKey(db_column='id_event', on_delete=django.db.models.deletion.CASCADE, to='database.event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='id_event',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
