# Generated by Django 5.0.6 on 2024-05-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_alter_evaluation_id_evaluation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborator',
            name='username',
        ),
        migrations.AddField(
            model_name='colaborator',
            name='num_colaborator',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
