# Generated by Django 5.0.6 on 2024-05-14 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_event_evaluated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='id_event',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
