# Generated by Django 5.0.6 on 2024-05-14 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_user_delete_population'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
