# Generated by Django 5.0.6 on 2024-05-14 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_user_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='work',
            new_name='role',
        ),
    ]
