# Generated by Django 5.0.6 on 2024-05-14 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_remove_colaborator_password_remove_colaborator_tier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='staus',
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
